# UMI LeRobot 2.1: state is eef delta pose, not joint angles.
name: umi_eef_left
dual_arm: false
dataset:
  _target_: caliball.dataset.lerobot_dataset.LeRobotDataset
  state_keys: observation.state
  state_processor:
    _target_: caliball.dataset.state_processors.UmiEEFProcessor
    start: 0
    stop: 10